project:
  type: website

website:
  title: "IS415-Harith"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"      
            text: "Hands-on Exercise 1"
      - text: "In-class Exercise"
        menu: 
          - href: "In-class_Ex/In-class_Ex02.html"      
            text: "In-class Exercise 2"
          - href: "In-class_Ex/In-class_Ex03.html"      
            text: "In-class Exercise 3"
          - href: "In-class_Ex/In-class_Ex04.html"      
            text: "In-class Exercise 4"
          - href: "In-class_Ex/In-class_Ex05.html"      
            text: "In-class Exercise 5"          
          - href: "In-class_Ex/In-class_Ex06.html"      
            text: "In-class Exercise 6"
          - href: "In-class_Ex/In-class_Ex07.html"      
            text: "In-class Exercise 7" 
          - href: "In-class_Ex/In-class_Ex08.html"      
            text: "In-class Exercise 8"
          - href: "In-class_Ex/In-class_Ex09.html"      
            text: "In-class Exercise 9"  
          - href: "In-class_Ex/In-class_Ex10.html"      
            text: "In-class Exercise 10"
          - href: "In-class_Ex/In-class_Ex11.html"      
            text: "In-class Exercise 11"   
  
            
      - text: "Take-home Exercise"
        menu: 
          - href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex1.html"      
            text: "Take-home Exercise 1"
          - href: "Take-home_Ex2/Take_home_exe2.html"      
            text: "Take-home Exercise 2"
          - href: "Take-home_Ex3/Take_home_Ex3.html"      
            text: "Take-home Exercise 3"


    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

