project:
  type: website

website:
  title: "IS415-Harith"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"      
            text: "Hands-on Exercise 1"
      - text: "In-class Exercise"
        menu: 
          - href: "In-class_Ex/In-class_Ex/In-class_Ex02.html"      
            text: "In-class Exercise 2"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

